# Generated by Django 4.2 on 2023-05-01 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="category",
        ),
        migrations.AddField(
            model_name="object",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects",
                to="inventory.category",
            ),
        ),
    ]
