# Generated by Django 4.2 on 2023-05-01 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_object_category_object_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="object",
            name="locations",
        ),
        migrations.AlterField(
            model_name="object",
            name="storage_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects",
                to="inventory.storagetype",
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="locations",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects",
                to="inventory.location",
            ),
            preserve_default=False,
        ),
    ]
