# Generated by Django 4.2 on 2023-05-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_remove_object_locations_alter_object_storage_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="object",
            old_name="locations",
            new_name="location",
        ),
    ]
