# Generated by Django 4.2 on 2023-05-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_rename_locations_object_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storagetype",
            name="locations",
        ),
        migrations.AddField(
            model_name="storagetype",
            name="location",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storage_type",
                to="inventory.location",
            ),
            preserve_default=False,
        ),
    ]
