# Generated by Django 4.2 on 2023-05-02 01:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_storagetype_locations_storagetype_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["id", "name"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["id", "name"]},
        ),
        migrations.AlterModelOptions(
            name="object",
            options={
                "ordering": ["id", "name", "location", "storage_type", "last_updated"]
            },
        ),
        migrations.AlterModelOptions(
            name="storagetype",
            options={"ordering": ["id", "name", "date_organized"]},
        ),
        migrations.AlterField(
            model_name="object",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="storage_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="objects",
                to="inventory.storagetype",
            ),
        ),
    ]
