# Generated by Django 4.2 on 2023-05-03 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_category_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_categories",
                to="inventory.category",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_locations",
                to="inventory.location",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="storage_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="object_storage_types",
                to="inventory.storagetype",
            ),
        ),
    ]
